apiVersion: v1
entries:
  opensandbox:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/alibaba/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/alibaba/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.0
    created: "2026-06-15T09:58:51.193302035Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.1.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: db857a2c9c1b34b4e7c76c90c47e39d144907e229214bd6e7ddcfcf3d86c9e7e
    home: https://github.com/alibaba/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/alibaba/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://open-sandbox.ai/helm/opensandbox-0.2.0.tgz
    version: 0.2.0
generated: "2026-06-15T09:58:51.191653565Z"
