apiVersion: v1
entries:
  opensandbox:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/opensandbox-group/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/opensandbox-group/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.3
    created: "2026-09-02T09:16:11.912473685Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.1
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.2.3
    - condition: opensandbox-node-agent.enabled
      name: opensandbox-node-agent
      repository: file://../opensandbox-node-agent
      version: 0.1.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: 8b4dfcf75a35a3c04862899c6c01f35de790bbede23a04a238fc54f5fa5caa1a
    home: https://github.com/opensandbox-group/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/opensandbox-group/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.5.tgz
    version: 0.2.5
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/opensandbox-group/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/opensandbox-group/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.3
    created: "2026-09-02T09:16:11.909538798Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.2.1
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: 124181bb02f8b897f183bd383add5ba25a1f0ff735c0046016d6f7fe7ad5d67e
    home: https://github.com/opensandbox-group/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/opensandbox-group/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.4.tgz
    version: 0.2.4
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/alibaba/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/alibaba/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.3
    created: "2026-09-02T09:16:11.908051768Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.2.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: 5aacbaa9ac6fc948d1997c1272ce59679151d3479728f29629dfdd44e9c9a7b4
    home: https://github.com/alibaba/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/alibaba/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.3.tgz
    version: 0.2.3
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/alibaba/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/alibaba/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.2
    created: "2026-09-02T09:16:11.906673151Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.1.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: 4cca14dc7037b48b63d55d6ed23489d970354347ab24f07081ec1153f6bee8a5
    home: https://github.com/alibaba/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/alibaba/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.2.tgz
    version: 0.2.2
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/alibaba/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/alibaba/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.1
    created: "2026-09-02T09:16:11.905275298Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.1.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: 77010e8e83cd21397a1c19df61da24dbfca5f921a60ed23873100b70d1394326
    home: https://github.com/alibaba/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/alibaba/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.1.tgz
    version: 0.2.1
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Helm Repository
          url: https://jaluma.github.io/OpenSandbox/helm
        - name: Documentation
          url: https://github.com/alibaba/OpenSandbox/blob/main/kubernetes/README.md
        - name: Support
          url: https://github.com/alibaba/OpenSandbox/issues
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 0.2.0
    created: "2026-09-02T09:16:11.903745017Z"
    dependencies:
    - name: opensandbox-controller
      repository: file://../opensandbox-controller
      version: 0.2.0
    - name: opensandbox-server
      repository: file://../opensandbox-server
      version: 0.1.0
    description: All-in-one Helm chart for deploying OpenSandbox controller and server
    digest: e6ac3c69bd13bf47f78469ea6e45e494c57493f7a51f879ec591354b801f6e14
    home: https://github.com/alibaba/OpenSandbox
    keywords:
    - sandbox
    - kubernetes
    - operator
    - api
    - lifecycle
    - batchsandbox
    kubeVersion: '>=1.21.1-0'
    maintainers:
    - email: opensandbox@example.com
      name: OpenSandbox Team
    name: opensandbox
    sources:
    - https://github.com/alibaba/OpenSandbox/tree/main/kubernetes
    type: application
    urls:
    - https://jaluma.github.io/OpenSandbox/helm/opensandbox-0.2.0.tgz
    version: 0.2.0
generated: "2026-09-02T09:16:11.900697081Z"
